### PR TITLE
Update to htm5 boilerplate v3.0

### PR DESCRIPTION
**Pull request by clivewalkden**
Hi,

Just finished updating the theme to use the new boilerplate version 3. Hope this helps keep this great project up to date.

Rgds...

Clive

### CODE REVIEW

**Comment by homosaur** [comment]
Hey Clive, I think this project has been abandoned, you are welcome to send commits to my branch at bytefair/eulerplate which is being maintained and updated.

**Comment by clivewalkden** [comment]
Yeah i think you're right there, it's best to clone yours directly rather than changing the pull request to your repo isn't it?

**Comment by homosaur** [comment]
yeah, I've already updated it to Boilerplate 3, but if you want to submit any other patches, I'll definitely consider them

**Comment by heff** [comment]
@clivewalkden see #22

**Pull request closed without merging**
